# Stacking

In [20]:
import numpy as np
 
x = np.arange(4).reshape(2, 2)
print(x)
print(x.shape)

[[0 1]
 [2 3]]
(2, 2)


In [14]:
y = x * 2
print(y)

[[0 2]
 [4 6]]


In [6]:
z = np.hstack((x, y))
print(z)
print(z.shape)

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [8]:
z = np.vstack((x, y))
print(z)
print(z.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [11]:
w = np.concatenate((x, y), axis = 1)
print(w)

[[0 1 4 5]
 [2 3 6 7]]


In [12]:
z = np.hstack((x, y))

In [13]:
print(z == w)

[[ True  True  True  True]
 [ True  True  True  True]]


In [18]:
depth_stack = np.dstack((x, y))
print(depth_stack)

[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]


In [19]:
print(depth_stack.shape)

(2, 2, 2)


In [22]:
print(np.column_stack((x, y)) == np.hstack((x,y)))

[[ True  True  True  True]
 [ True  True  True  True]]


In [26]:
print(np.row_stack((x, y)) == np.vstack((x, y)))

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


/tmp/ipykernel_238499/4105709248.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((x, y)) == np.vstack((x, y)))
