# List vs Arrays

In [1]:
list_two = list(range(1, 4))
list_three = list(range(1, 4))
list_sum = []

for i in range(3):
    list_two[i] = list_two[i] ** 2
    list_three[i] = list_three[i] ** 3
    list_sum.append(list_two[i] + list_three[i])

print(list_sum)

[2, 12, 36]


In [2]:
import numpy as np

array_two = np.arange(1, 4) ** 2
print(array_two)
array_three = np.arange(1, 4) ** 3
print(array_three)
array_sum = array_two + array_three
print(array_sum)

[1 4 9]
[ 1  8 27]
[ 2 12 36]


In [3]:
np.power(np.array([1, 2, 3]), 4)

array([ 1, 16, 81])

In [4]:
sample_arrey = np.array([1, 2, 3])
np.negative(np.array([1, 2, 4]))

array([-1, -2, -4])

In [5]:
np.exp(sample_arrey)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [6]:
np.log(sample_arrey)

array([0.        , 0.69314718, 1.09861229])

In [7]:
np.sin(sample_arrey)

array([0.84147098, 0.90929743, 0.14112001])