# Multidimensionall Dimension Reshaping

In [5]:
import numpy as np

x = np.arange(18).reshape(3,2,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [10]:
print(x[1, 1, 1])
print(x[1, :2, :3])

10
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
comparison_operation = x > 5
print(comparison_operation)

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]


In [17]:
print(x[x > 5])

[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [18]:
print(x.max())

17


In [19]:
print(x.min())

0
