# 1D Slicing and reshaping

In [2]:
import numpy as np

x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [4]:
print(x[2:7])

[3 4 5 6 7]


In [10]:
import numpy as np

x = np.arange(18).reshape(3, 3, -1)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
