# Stacking

In [5]:
import numpy as np
 
x = np.arange(4).reshape(2, 2)
print(x)
print(x.shape)

[[0 1]
 [2 3]]
(2, 2)


In [2]:
y = np.arange(4, 8).reshape(2,2)
print(y)

[[4 5]
 [6 7]]


In [6]:
z = np.hstack((x, y))
print(z)
print(z.shape)

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [7]:
z = np.vstack((x, y))
print(z)
print(z.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
