# Matrix multiplication

In [17]:
import numpy as np

Matrix_A = np.arange(6).reshape(2, 3)
print(Matrix_A)
Matrix_B = np.arange(6).reshape(3, 2)
print(Matrix_B)
#Matrix_A * Matrix_B

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [19]:
product = np.matmul(Matrix_A, Matrix_B)
print(product)

[[10 13]
 [28 40]]


In [20]:
print(Matrix_A @ Matrix_B)


[[10 13]
 [28 40]]
