# Multidimensional Arrays

In [11]:
import numpy as np

x = np.arange(3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x, y, z], dtype = np.int8)
print(multi_array)
print(multi_array.shape)
multi_array[2,2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


np.int8(8)

In [9]:

w = np.linspace(1, 10)
print(w)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [12]:
print(multi_array.dtype)

int8
