# Manipulating Array Shapes

In [1]:
import numpy as np

x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
revelled_arrey = x.ravel()
print(revelled_arrey)

[0 1 2 3 4 5 6 7 8]


In [4]:
flattened_array = x.flatten()
flattened_array[2] = 1000000000000
print(flattened_array)

[            0             1 1000000000000             3             4
             5             6             7             8]


In [7]:
y = np.arange(9)
y.shape = [3, 3]
print(y.transpose())

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [8]:
print(np.resize(y, (6, 6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [16]:
print(np.zeros((6), dtype = int))
print(np.ones((6), dtype = int))

[0 0 0 0 0 0]
[1 1 1 1 1 1]


In [17]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
np.random.rand(4, 4)

array([[0.80763047, 0.21694668, 0.45629001, 0.75255095],
       [0.44336372, 0.31828399, 0.02103328, 0.43691744],
       [0.7396443 , 0.9304245 , 0.39439583, 0.4719934 ],
       [0.79738553, 0.20100511, 0.18587298, 0.24533067]])